# Generated by Django 6.0.3 on 2026-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(editable=False, max_length=20, unique=True)),
                ('prenom', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('etudiant', 'Etudiant'), ('enseignant', 'Enseignant'), ('personnel', 'Personnel administratif')], max_length=20)),
            ],
        ),
    ]
