# Generated by Django 6.0.3 on 2026-03-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0002_alter_emprunt_livre'),
        ('livres', '0002_livre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='livres.livre'),
        ),
    ]
