# Generated by Django 6.0.3 on 2026-03-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('annee_publication', models.IntegerField()),
                ('nbr_exemplaires', models.IntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté'), ('reserve', 'Réservé'), ('perdu', 'Perdu'), ('endommage', 'Endommagé')])),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='livres.auteur')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='livres.genre')),
            ],
        ),
    ]
