# Generated by Django 6.0.3 on 2026-03-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='description',
            field=models.CharField(default='...', max_length=600),
        ),
    ]
